source ~/.local/functions.sh
source ~/.local/exports.sh
source ~/.local/aliases.sh
source ~/.local/functions.sh
export PATH=/home/akinozgen/easy_rust/gcsplit/bin/Debug:$PATH
export PATH=/home/akinozgen/easy_rust/gcsplit/SPAdes-3.11.1-Linux/bin:$PATH
export PATH=/home/akinozgen/easy_rust/gcsplit/KmerStream:$PATH
export PATH=/home/akinozgen/easy_rust/gcsplit/bin/Debug:$PATH
export PATH=/home/akinozgen/easy_rust/gcsplit/SPAdes-3.11.1-Linux/bin:$PATH
export PATH=/home/akinozgen/easy_rust/gcsplit/KmerStream:$PATH
